### ISSUE TITLE
Improved README?

### ISSUE THREAD

**Issue by thundergolfer** [ppke-nlpg/whats-wrong-python#1]
Hey, 

I saw the original Java library when looking at UCL's Machine Reading Group, and may be interested in contributing to this python port. 

The code is well-documented, but I think it would be helpful if the README contained more information on project status. Like the following: 

* Link to `CONTRIBUTING.md` document
* Details of what's been implemented
* Details of what's left to be implemented
* A demo of existing functionality
* An "Installation" section
* A "Development" section for directions on how to develop on this project

### Some other things that would be good

* Change the name of the repo. Why is it so weirdly formatted? What is "SVG" in there for? Couldn't it just be `ppke-nlpg/Whats-Wrong-Python`?
* Tests! Where are the tests!

**Comment by dlazesz** [comment]
Thank you for your suggestions!
We're currently implementing a major change in the structure of the program. (We plan to separate the GUI from the logic.)

Please check back in a week or two. I'll implement your suggestions and draft our plans by then.

**Comment by thundergolfer** [comment]
> We plan to separate the GUI from the logic

Haha that sounds like a wonderful idea. 

Look forward to seeing how this project develops.

**Comment by dlazesz** [comment]
Unfortunately the development is going slower, than we expected, but there are some progress already.

I've applied your suggestions in the README.md.
There are still some things that are not clear even for us yet, these items are currently missing.
I'll update them as soon there is some progress.

Could check the README.md and tell me how you like it?

**Comment by thundergolfer** [comment]
I'm subscribed to the repository and you have been working pretty steady on it. Slow progress is fine. The `README.md` is heaps better now 👍

**Comment by dlazesz** [comment]
If you do not object, i'll close this bug as the README.md is almost perfect. :)
