### ISSUE TITLE
Adding Code and Documentation style information

### ISSUE THREAD

**Issue by thundergolfer** [ppke-nlpg/whats-wrong-python#2]
This codebase differs significantly from Python's [PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/). Code style conventions are different and documentation is different. 

For example python modules here are named in `CamelCase.py`, not like this: `this_is_a_module.py`. This means that importing a module looks the same as importing a class. Classes are files/modules in Java, but not in Python. 

Also your docstrings for functions are not PEP8, what style are they? Again, they look similar to JavaDoc docstrings. 

-----

If you could add details about this projects code and documentation conventions it would make it easier to contribute. Though I would consider simply switching the codebase to adhere to PEP8.

**Comment by dlazesz** [comment]
Long story short:

We used the non-pythonic style to make the diffing with the JAVA code easier.
Now, we are doing a transition to a PEP8 convenient format and  applying [Google style docstrings](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). 

Some of the code still have the old look. We are working on it.

I'll add this information to the README.md as soon the next round of refactoring concerning the rendering stuff completes.

**Comment by dlazesz** [comment]
I think this issue is solved now.
Some features still incomplete, but the code style should be OK now.

If you find anything I'll fix it.
